### ISSUE TITLE
Changing the code to accept (Plugin-name).indigoPlugin first level subfolder

### ISSUE THREAD

**Issue by tenallero** [jheddings/indigo-ghpu#2]
Hi,

Thanks for your great code.

I am uploading my plugin´s code to github. So, I found useful to include your tool for check/download new releases.
I have found that many developers place a subfolder **(Plugin-name).indigoPlugin** at first level. This is useful if you want to create a zip file directly from your working files.
So, I did the same:

https://github.com/IndigoDomotics/alexa-hue-bridge
https://github.com/IndigoDomotics/GhostXML
https://github.com/RogueProeliator/IndigoPlugin-TiVo-Network-Remote
https://github.com/tenallero/Indigo-ThinkingCleaner

I see you tool follows the "convention" that the first subfolder must be "**Contents**". So, your methods _verifyPluginInfo and _installRelease raise an exception if this "convention" is not followed inside the tarball

I have modified your ghpu.py file to adapt it to check if a prior level subfolder named **(Plugin-name).indigoPlugin** exists.

_verifyPluginInfo(self, zipfile):

```
subfolder = self.plugin.pluginDisplayName + '.indigoPlugin'
topdir = zipfile.namelist()[0]

# read and confirm the plugin info contained in the zipfile   
plistFile = os.path.join(topdir, subfolder, 'Contents', 'Info.plist')
if not plistFile in zipfile.namelist():
     plistFile = os.path.join(topdir, 'Contents', 'Info.plist')
```

_installRelease(self, release):

```
subfolder = os.path.join(newPluginDir, self.plugin.pluginDisplayName + '.indigoPlugin')
if (os.path.exists(subfolder)):
    subprocess.call(['open', subfolder])
else:
    subprocess.call(['open', newPluginDir])
```

Can you please consider these changes and include them in your code?

**Comment by jheddings** [comment]
Excellent suggestions!  I will add those to the plugin and issue a new release.

Thanks for the contribution!
-jh

**Comment by jheddings** [comment]
I used your example and made a configuration file for the plugin path…  Would you mind trying ti and see if it works for you?  Note that you will need to create the configuration file to set up the plugin now.

https://github.com/jheddings/indigo-ghpu https://github.com/jheddings/indigo-ghpu

-jh

**Comment by tenallero** [comment]
Hi,

I have been trying your latest release.
I get a strange "error" about ID Mismatch.
You can see Indigo event log screen capture.
Modifing your source, I have included two debug output lines (begin with 3 asterisk) that output the values for pInfo.id and self.plugin.pluginId.
The values are the same! But your comparative instruction gives a mismatched error  ??!!

My testing plugin (with your latest update relase) is on:
https://github.com/tenallero/Indigo-Ping

![updatererror](https://cloud.githubusercontent.com/assets/17275751/13748800/a8ae38f0-e9fe-11e5-848e-f9b0f4d4bf8b.png)

**Comment by jheddings** [comment]
Thanks for the testing…  I think there is an issue comparing the tuple value in different versions of Python.  I’ll try to get that sorted out soon and reply with an update.

-jh

**Comment by tenallero** [comment]
I am not strong with Python.
But, doing str(self.plugin.pluginId) == str(pInfo.id) also returns False
Strange

**Comment by jheddings** [comment]
I found the issue...  I checked in a new version with a fix.  Would you verify that it fixes your issue?

**Comment by tenallero** [comment]
Well,

Now, no raised exception during comparation.
Seems to follow the next steps.
The event log says "Installation complete" **BUT Indigo DOES NOT shown any dialog** about installing.
So, the*\* plugin is not updated**.
Is it realy doing the opening of ".indigoPlugin" file?

As you can see at the screen capture ... the release from github is 0.0.11 and the currently installed is 0.0.7

I have rebooted the mac mini where Indigo is running to see if the problem is a temporar file or folder.

![updatenotopen](https://cloud.githubusercontent.com/assets/17275751/13772835/806bb9c4-ea96-11e5-9d3a-2a153cf3fc3a.png)

**Comment by tenallero** [comment]
Hi,

I have done some debugging,

the method _installPlugin is correct
pluginPath variable has a good value

The problem is that subprocess.call (['open',pluginPath]) seems to be asyncronous
And, somewhere in your code or other OSX process is removing the folder to be installed.

So, the open process does nothing or says invalid Info.plist, because nothing is found to be open or incomplert "indigoPlugin" container is found.

If you comment your subprocess (open)  line of code ... you can see (using Finder) that the  /tmp/tenallero-Indigo-Ping-7ff6c68/Ping.indigoPlugin  folder appears and disapears.

**Comment by jheddings** [comment]
You are absolutely right...  I was trying to clean up the zip file after the installation, but because it is happening asynchronously, the filter is disappearing before Indigo can install it.  I'm working on a fix now.

**Comment by jheddings** [comment]
I just pushed a fix for this...  It should take care of the issue.  If you are still seeing problems, would you mind opening a new issue?  Thanks!
